apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: markdown-linting-pipeline-run-
spec:
  pipelineRef:
    name: markdown-linting-pipeline
  params:
    - name: source-repo
      value: https://github.com/upslopeio/lint-markdown-files.git
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi